# Change these first
owner: Sdator # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: MyBlog
    url: https://sdator.github.io
  - name: BinEditTool # 二进制编辑工具
    url: https://sdator.github.io/tools/fchack/
  - name: War3C2I # 魔兽3字符编码转换器
    url: https://sdator.github.io/tools/war3/


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Home
  introTitle: "**状态页**"
  introMessage: test
  navbar:
    - title: Blog
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
